#include "viva.h"

namespace viva 
{
    namespace Input 
    {
        enum class MouseKey : int
        {
            Left = 0x01,
            Right = 0x02,
            Middle = 0x04
        };

        enum class KeyboardKey : int
        {
            BackSpace = 0x08,
            Tab = 0x09,
            Enter = 0x0D, //both enter and num enter
            Shift = 0x10, //both left and right
            Control = 0x11,//ctrl, both l and r
            Alt = 0x12, //alt, both l and r
            PauseBreak = 0x13, //better dont use this
            CapsLock = 0x14,
            Escape = 0x1B,
            Space = 0x20,
            PageUp = 0x21,
            PageDown = 0x22,
            End = 0x23,
            Home = 0x24,
            Left = 0x25,
            Up = 0x26,
            Right = 0x27,
            Down = 0x28,
            PrintScreen = 0x2C,
            Insert = 0x2D,
            Delete = 0x2E,
            Key0 = '0',
            Key1 = '1',
            Key2 = '2',
            Key3 = '3',
            Key4 = '4',
            Key5 = '5',
            Key6 = '6',
            Key7 = '7',
            Key8 = '8',
            Key9 = '9',
            KeyA = 'A',
            KeyB = 'B',
            KeyC = 'C',
            KeyD = 'D',
            KeyE = 'E',
            KeyF = 'F',
            KeyG = 'G',
            KeyH = 'H',
            KeyI = 'I',
            KeyJ = 'J',
            KeyK = 'K',
            KeyL = 'L',
            KeyM = 'M',
            KeyN = 'N',
            KeyO = 'O',
            KeyP = 'P',
            KeyQ = 'Q',
            KeyR = 'R',
            KeyS = 'S',
            KeyT = 'T',
            KeyU = 'U',
            KeyV = 'V',
            KeyW = 'W',
            KeyX = 'X',
            KeyY = 'Y',
            KeyZ = 'Z',
            WinLeft = 0x5B,
            WinRight = 0x5C,
            Menu = 0x5D,
            RightMenu = 0x5D, //same as menu
            Num0 = 0x60,
            Num1 = 0x61,
            Num2 = 0x62,
            Num3 = 0x63,
            Num4 = 0x64,
            Num5 = 0x65,
            Num6 = 0x66,
            Num7 = 0x67,
            Num8 = 0x68,
            Num9 = 0x69,
            NumMultiply = 0x6A,
            NumPlus = 0x6B,
            NumMinus = 0x6D,
            NumDot = 0x6E,
            NumDivide = 0x6F,
            F1 = 0x70,
            F2 = 0x71,
            F3 = 0x72,
            F4 = 0x73,
            F5 = 0x74,
            F6 = 0x75,
            F7 = 0x76,
            F8 = 0x77,
            F9 = 0x78,
            F10 = 0x79,
            F11 = 0x7A,
            F12 = 0x7B,
            F13 = 0x7C,
            F14 = 0x7D,
            F15 = 0x7E,
            F16 = 0x7F,
            F17 = 0x80,
            F18 = 0x81,
            F19 = 0x82,
            F20 = 0x83,
            F21 = 0x84,
            F22 = 0x85,
            F23 = 0x86,
            F24 = 0x87,
            Numlock = 0x90,
            ScrollLock = 0x91,
            LeftShift = 0xA0,
            RightShift = 0xA1,
            LeftControl = 0xA2,
            RightControl = 0xA3,
            LeftAlt = 0xA4,
            RightAlt = 0xA5,
            Semicolon = 0xBA,
            Plus = 0xBB,
            Equals = 0xBB, //same as Plus
            Comma = 0xBC,
            Minus = 0xBD,
            Period = 0xBE,
            Slash = 0xBF,
            Tilde = 0xC0,
            LeftBracket = 0xDB,
            BackSlash = 0xDC,
            RightBracket = 0xDD,
            Apostrophe = 0xDE,
        };

        enum class GamepadKey : int
        {
            Up = 1,
            Down = 2,
            Left = 4,
            Right = 8,
            Start = 16,
            Back = 32,
            LeftStick = 64,
            RightStick = 128,
            LB = 256,
            RB = 512,
            _1024 = 1024,
            _2048 = 2048,
            A = 4096,
            B = 8192,
            X = 16384,
            Y = 32768,
        };
    }
}